[project]
name = "LucyHubClient"
version = "0.0.1a"
description = "A smart home hub client for LucyServer."
requires-python = ">=3.10"
dependencies = [
    "asyncio",
    "websockets",
    "pyaudio",
    "numpy",
    "requests",
    "python-dotenv",
    "torch==2.7.0",
    "torchaudio==2.7.0",
    "websockets",
    "scipy",
    "pyyaml"
]

[tool.setuptools.package-data]
"lucyhubclient.sounds" = ["*.wav"]
"lucyhubclient.templates" = ["*.html"]
"lucyhubclient.tools.clock_util" = ["*.wav"]


[project.optional-dependencies]
# UI Providers
ui_selenium = ["selenium", "webdriver_manager"]
ui_pywebview = ["pywebview[qt]"]

# Detect Speech Providers
ds_vad = ["silero-vad"]
ds_wakeword = ["openwakeword", "silero-vad"]

# Voice Providers
tts_elevenlabs = ["elevenlabs"]
tts_kokoro = ["kokoro"]