[project]
name = "LucyHubClient"
version = "0.0.1a"
description = "A smart home hub client for LucyServer."
requires-python = ">=3.10"
dependencies = [
    "asyncio",
    "websockets",
    "pyaudio",
    "numpy",
    "requests",

    "torch==2.7.0",
    "torchaudio==2.7.0",
    "websockets",
    "scipy",
    "pyyaml",
    "openwakeword",
    "silero-vad",
    "selenium",
    "webdriver_manager"
]

[tool.setuptools.package-data]
"lucyhubclient.sounds" = ["*.wav"]
"lucyhubclient.templates" = ["*.html"]
"lucyhubclient.tools.clock_util" = ["*.wav"]